-- Supabase/PostgreSQL migration script for Nia Jaya Stock
-- Generated from MySQL dump: nia_jaya_stock.sql

BEGIN;

-- Drop old tables if needed (safe for re-run in dev)
DROP TABLE IF EXISTS stock_opname CASCADE;
DROP TABLE IF EXISTS barang_kosong CASCADE;
DROP TABLE IF EXISTS keuangan CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS barang CASCADE;

-- users
CREATE TABLE users (
  id_user INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50),
  password VARCHAR(255),
  nama_lengkap VARCHAR(100),
  role VARCHAR(20) CHECK (role IN ('owner', 'karyawan'))
);

-- barang
CREATE TABLE barang (
  id_barang INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kode_barang VARCHAR(20),
  nama_barang VARCHAR(100),
  kategori VARCHAR(50),
  stok INTEGER,
  harga NUMERIC(12,2),
  satuan VARCHAR(20)
);

-- barang_kosong
CREATE TABLE barang_kosong (
  id_kosong INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_barang VARCHAR(100),
  status_barang VARCHAR(20) CHECK (status_barang IN ('Habis', 'Hampir Habis')),
  tanggal_input DATE,
  input_oleh VARCHAR(100)
);

-- keuangan
CREATE TABLE keuangan (
  id_keuangan INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tanggal DATE,
  pemasukan NUMERIC(12,2),
  pengeluaran NUMERIC(12,2),
  keterangan TEXT
);

-- stock_opname
CREATE TABLE stock_opname (
  id_opname INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_barang INTEGER,
  stok_sistem INTEGER,
  stok_fisik INTEGER,
  selisih INTEGER,
  tanggal_opname DATE,
  petugas VARCHAR(100),
  CONSTRAINT stock_opname_id_barang_fkey
    FOREIGN KEY (id_barang) REFERENCES barang(id_barang)
    ON DELETE CASCADE
);

-- Data inserts
INSERT INTO barang (id_barang, kode_barang, nama_barang, kategori, stok, harga, satuan) VALUES
(3, '3', 'pulpen', 'ATK', 36, 3000.00, 'Pcs'),
(4, '2', 'hvs a4', 'Kertas', 10, 40000.00, 'Rim');

INSERT INTO barang_kosong (id_kosong, nama_barang, status_barang, tanggal_input, input_oleh) VALUES
(2, 'pulpen standard', 'Hampir Habis', '2026-05-24', 'karyawan'),
(3, 'penggaris 30cm', 'Habis', '2026-05-24', 'karyawan'),
(4, 'correction tape 7m', 'Habis', '2026-05-24', 'karyawan'),
(6, 'buku gambar a4', 'Habis', '2026-06-03', 'karyawan');

INSERT INTO keuangan (id_keuangan, tanggal, pemasukan, pengeluaran, keterangan) VALUES
(1, '2026-06-03', 5000000.00, 3000000.00, 'pengeluaran tertentu');

INSERT INTO stock_opname (id_opname, id_barang, stok_sistem, stok_fisik, selisih, tanggal_opname, petugas) VALUES
(8, 3, 36, 20, -16, '2026-06-03', 'karyawan'),
(9, 4, 10, 12, 2, '2026-06-03', 'karyawan');

INSERT INTO users (id_user, username, password, nama_lengkap, role) VALUES
(1, 'owner', 'scrypt:32768:8:1$DVlrSNqZ5Wqqn7z5$283465a26c71983d65bf39266780849055c5e9906a67655525c9a76467c506884b06db9a7f6bbb1bb28bdb94f7422d90695d91eda14c12fdeae10a0811f3c26b', 'Owner Nia Jaya', 'owner'),
(2, 'karyawan', 'scrypt:32768:8:1$Opts0jYgSuodSo2d$d0d1abc972d645a6d9faf19705335f4e19db024e8b54d87f37e33d6de804eb837846578087cb7fbde0413c6f75b2ca2a64f6c7943a31f04a550df77bdc195680', 'Karyawan Nia Jaya', 'karyawan');

-- Reset identity sequences so next insert continues correctly
SELECT setval(pg_get_serial_sequence('users', 'id_user'), COALESCE((SELECT MAX(id_user) FROM users), 1), true);
SELECT setval(pg_get_serial_sequence('barang', 'id_barang'), COALESCE((SELECT MAX(id_barang) FROM barang), 1), true);
SELECT setval(pg_get_serial_sequence('barang_kosong', 'id_kosong'), COALESCE((SELECT MAX(id_kosong) FROM barang_kosong), 1), true);
SELECT setval(pg_get_serial_sequence('keuangan', 'id_keuangan'), COALESCE((SELECT MAX(id_keuangan) FROM keuangan), 1), true);
SELECT setval(pg_get_serial_sequence('stock_opname', 'id_opname'), COALESCE((SELECT MAX(id_opname) FROM stock_opname), 1), true);

COMMIT;
